<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        \DB::table('users')->insert([
            [
                'id' => '1',
                'hoten' => 'Test',
                'email' => 'test@gmail.com',
                'gioitinh' => 0,
                'ngaysinh' => '1989-12-01',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 1,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH1111111',
                'hoten' => 'admin',
                'email' => 'admin@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-01-28',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 1,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH123456',
                'hoten' => 'Thay hung',
                'email' => 'hung@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '1989-01-01',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 1,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH222222',
                'hoten' => 'Giáo viên',
                'email' => 'giaovien@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-02-27',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH333333',
                'hoten' => 'Sinh Viên',
                'email' => 'sinhvien@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-02-27',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200608',
                'hoten' => 'Trịnh Minh Giàu',
                'email' => 'giau@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-02-27',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200854',
                'hoten' => 'Võ Lê Minh Khang',
                'email' => 'khang@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-10-26',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200855',
                'hoten' => 'Nguyễn Hoàng Khoa',
                'email' => 'khoa@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-06-13',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201068',
                'hoten' => 'Vũ Thành Nhật Minh',
                'email' => 'minh@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-07-22',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 1,
                'makhoa' => null,
            ],
            [
                'id' => 'DH52201508',
                'hoten' => 'Võ Lê Minh Thịnh',
                'email' => 'thinh@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-10-26',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201659',
                'hoten' => 'Phan Thanh Trọng',
                'email' => 'trong@gmail.com',
                'gioitinh' => 1,
                'ngaysinh' => '2004-01-28',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'sodienthoai' => null,
                'manhomquyen' => 1,
                'makhoa' => null,
            ],
        ]);


        \DB::table('users')->insert([
            [
                'id' => 'DH1',
                'hoten' => 'Ngô Xuân Bách',
                'email' => 'ngoxuanbach@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH2',
                'hoten' => 'Bùi Nhật Bằng',
                'email' => 'buinhatbang@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH3',
                'hoten' => 'Đoàn Trình Dục',
                'email' => 'doantrInhduc@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH4',
                'hoten' => 'Lê Kim Dung',
                'email' => 'lekimdung@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH5',
                'hoten' => 'Lê Thị Mỹ Dung',
                'email' => 'lethimydung@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH6',
                'hoten' => 'Trịnh Thanh Duy',
                'email' => 'trinhthanhduy@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH7',
                'hoten' => 'Lê Triệu Ngọc Đức',
                'email' => 'letrieunagocduc@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH8',
                'hoten' => 'Hồ Hải',
                'email' => 'hohai@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH9',
                'hoten' => 'Nguyễn Thái Hoà',
                'email' => 'nguyenthaihoa@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH10',
                'hoten' => 'Trần Văn Hùng',
                'email' => 'tranvanhung@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH11',
                'hoten' => 'Nguyễn Ngọc Lâm',
                'email' => 'nguyenngoclam@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH12',
                'hoten' => 'Hồ Đình Khả',
                'email' => 'hodinhkha@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH13',
                'hoten' => 'Trần Thị Mỹ Huỳnh',
                'email' => 'tranthimyhuynh@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH14',
                'hoten' => 'Nguyễn Trọng Nghĩa',
                'email' => 'nguyentrongnghia@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH15',
                'hoten' => 'Nguyễn Kiều Oanh',
                'email' => 'nguyenkieuoanh@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH16',
                'hoten' => 'Hoàng Xuân Phương',
                'email' => 'hoangxuanphuong@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH17',
                'hoten' => 'Đặng Trường Sơn',
                'email' => 'dangtruongson@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH18',
                'hoten' => 'Trần Trung Tâm',
                'email' => 'trantrungtam@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH19',
                'hoten' => 'Nguyễn Trần Phúc Thịnh',
                'email' => 'nguyentranphucthinh@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH20',
                'hoten' => 'Nguyễn Lạc An Thư',
                'email' => 'nguyenlacanthu@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH21',
                'hoten' => 'Dương Thái Thương',
                'email' => 'duongthaIthuong@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH22',
                'hoten' => 'Ngô Thị Bảo Trân',
                'email' => 'ngothibaotran@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH23',
                'hoten' => 'Hà Vũ Tuân',
                'email' => 'havutuan@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH24',
                'hoten' => 'Nguyễn Thanh Tùng',
                'email' => 'nguyenthanhtung@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH25',
                'hoten' => 'Lương An Vinh',
                'email' => 'luonganvinh@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH26',
                'hoten' => 'Hà Anh Vũ',
                'email' => 'haanhvu@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH27',
                'hoten' => 'Nguyễn Thị Thanh Xuân',
                'email' => 'nguyenthithanhxuan@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH28',
                'hoten' => 'Trần Thị Như Ý',
                'email' => 'tranthinhuy@stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 2,
                'makhoa' => 3,
            ],
        ]);

        \DB::table('users')->insert([
            [
                'id' => 'DH52200365',
                'hoten' => 'Nguyễn Đặng Quốc Bảo',
                'email' => 'DH52200365@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200391',
                'hoten' => 'Kim Văn Bình',
                'email' => 'DH52200391@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200415',
                'hoten' => 'Phan Văn Thế Chương',
                'email' => 'DH52200415@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200423',
                'hoten' => 'Lâm Dũ Cường',
                'email' => 'DH52200423@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200439',
                'hoten' => 'Nguyễn Hải Đăng',
                'email' => 'DH52200439@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200452',
                'hoten' => 'Nguyễn Võ Thành Danh',
                'email' => 'DH52200452@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200454',
                'hoten' => 'Cao Tấn Đạt',
                'email' => 'DH52200454@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200472',
                'hoten' => 'Lê Văn Đạt',
                'email' => 'DH52200472@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200490',
                'hoten' => 'Nguyễn Tiến Đạt',
                'email' => 'DH52200490@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200492',
                'hoten' => 'Phạm Xuân Đạt',
                'email' => 'DH52200492@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200499',
                'hoten' => 'Trần Tuấn Đạt',
                'email' => 'DH52200499@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72201972',
                'hoten' => 'Trần Thị Hoàng Diệp',
                'email' => 'DH72201972@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200508',
                'hoten' => 'Trần Đình Định',
                'email' => 'DH52200508@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200529',
                'hoten' => 'Bùi Hoàng Đức Dũng',
                'email' => 'DH52200529@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200539',
                'hoten' => 'Phạm Quang Dũng',
                'email' => 'DH52200539@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72201989',
                'hoten' => 'Ngô Thị Thùy Dương',
                'email' => 'DH72201989@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200554',
                'hoten' => 'Bùi Khắc Duy',
                'email' => 'DH52200554@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200558',
                'hoten' => 'Đoàn Trường Duy',
                'email' => 'DH52200558@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72201998',
                'hoten' => 'Đinh Ngọc Phương Duyên',
                'email' => 'DH72201998@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202000',
                'hoten' => 'Lê Thị Duyên',
                'email' => 'DH72202000@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200601',
                'hoten' => 'Nguyễn Hoàng Giang',
                'email' => 'DH52200601@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200616',
                'hoten' => 'Hứa Khắc Hải',
                'email' => 'DH52200616@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200618',
                'hoten' => 'Nguyễn Hoàng Hải',
                'email' => 'DH52200618@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200662',
                'hoten' => 'Nguyễn Minh Hiền',
                'email' => 'DH52200662@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202052',
                'hoten' => 'Trần Thị Hiền',
                'email' => 'DH72202052@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200670',
                'hoten' => 'Bành Kim Hiếu',
                'email' => 'DH52200670@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200671',
                'hoten' => 'Bùi Khắc Hiếu',
                'email' => 'DH52200671@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200681',
                'hoten' => 'Ngô Trần Trung Hiếu',
                'email' => 'DH52200681@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200683',
                'hoten' => 'Nguyễn Thanh Hiếu',
                'email' => 'DH52200683@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200705',
                'hoten' => 'Lê Ngọc Hoàng',
                'email' => 'DH52200705@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200752',
                'hoten' => 'Vòng Kiên Hưng',
                'email' => 'DH52200752@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200806',
                'hoten' => 'Trần Nguyễn Quốc Huy',
                'email' => 'DH52200806@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200815',
                'hoten' => 'Nguyễn Văn Huyền',
                'email' => 'DH52200815@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202100',
                'hoten' => 'Thái Thị Mỹ Huyền',
                'email' => 'DH72202100@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200821',
                'hoten' => 'Huỳnh Đông Kha',
                'email' => 'DH52200821@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200859',
                'hoten' => 'Nguyễn Phan Hữu Khanh',
                'email' => 'DH52200859@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200897',
                'hoten' => 'Cao Hoàng Đăng Khoa',
                'email' => 'DH52200897@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200901',
                'hoten' => 'Dương Nguyễn Đăng Khoa',
                'email' => 'DH52200901@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200915',
                'hoten' => 'Phan Anh Khoa',
                'email' => 'DH52200915@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200945',
                'hoten' => 'Lê Phạm Tuấn Kiệt',
                'email' => 'DH52200945@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200948',
                'hoten' => 'Ngô Anh Kiệt',
                'email' => 'DH52200948@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200968',
                'hoten' => 'Lý Tường Lâm',
                'email' => 'DH52200968@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202140',
                'hoten' => 'Nguyễn Trần Thu Lan',
                'email' => 'DH72202140@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200975',
                'hoten' => 'Hoàng Đặng Diệp Lân',
                'email' => 'DH52200975@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202143',
                'hoten' => 'Ngô Thị Bích Liên',
                'email' => 'DH72202143@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200986',
                'hoten' => 'Nguyễn Thế Linh',
                'email' => 'DH52200986@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202154',
                'hoten' => 'Trần Ngọc Trúc Linh',
                'email' => 'DH72202154@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52200998',
                'hoten' => 'Nguyễn Hữu Lộc',
                'email' => 'DH52200998@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201015',
                'hoten' => 'Đoàn Nam Vân Long',
                'email' => 'DH52201015@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201031',
                'hoten' => 'Triệu Kim Long',
                'email' => 'DH52201031@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202177',
                'hoten' => 'Võ Thị Ngọc Mai',
                'email' => 'DH72202177@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201056',
                'hoten' => 'Lưu Quang Minh',
                'email' => 'DH52201056@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201057',
                'hoten' => 'Lưu Thái Minh',
                'email' => 'DH52201057@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201065',
                'hoten' => 'Trần Tiến Minh',
                'email' => 'DH52201065@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201066',
                'hoten' => 'Trịnh Nhật Minh',
                'email' => 'DH52201066@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202184',
                'hoten' => 'Liễu Thị Kiều My',
                'email' => 'DH72202184@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201081',
                'hoten' => 'Nguyễn Văn Nam',
                'email' => 'DH52201081@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201083',
                'hoten' => 'Trần Hoa Nam',
                'email' => 'DH52201083@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202208',
                'hoten' => 'Nguyễn Đạt Ngọc Ngân',
                'email' => 'DH72202208@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202210',
                'hoten' => 'Nguyễn Kim Ngân',
                'email' => 'DH72202210@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201099',
                'hoten' => 'Nguyễn Phước Nghĩa',
                'email' => 'DH52201099@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201152',
                'hoten' => 'Nguyễn Minh Nhật',
                'email' => 'DH52201152@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH72202247',
                'hoten' => 'Lê Yến Nhi',
                'email' => 'DH72202247@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52111440',
                'hoten' => 'Huỳnh Nhu',
                'email' => 'DH52111440@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201181',
                'hoten' => 'Huỳnh Nguyễn Tấn Phát',
                'email' => 'DH52201181@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201183',
                'hoten' => 'Lai Thuận Phát',
                'email' => 'DH52201183@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201207',
                'hoten' => 'Lê Chí Phong',
                'email' => 'DH52201207@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201201',
                'hoten' => 'Trần Tuấn Phát',
                'email' => 'DH52201201@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 1,
            ],
            [
                'id' => 'DH52201248',
                'hoten' => 'Nguyễn Thanh Phúc',
                'email' => 'DH52201248@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201250',
                'hoten' => 'Nguyễn Trường Phúc',
                'email' => 'DH52201250@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201253',
                'hoten' => 'Phan Hữu Phúc',
                'email' => 'DH52201253@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201254',
                'hoten' => 'Thiều Hữu Phúc',
                'email' => 'DH52201254@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201257',
                'hoten' => 'Trần Minh Phúc',
                'email' => 'DH52201257@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201258',
                'hoten' => 'Trần Thanh Hoài Phúc',
                'email' => 'DH52201258@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201275',
                'hoten' => 'Khưu Ngọc Thanh Phương',
                'email' => 'DH52201275@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201290',
                'hoten' => 'Nguyễn Hồng Quân',
                'email' => 'DH52201290@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201315',
                'hoten' => 'Trần Nhựt Quang',
                'email' => 'DH52201315@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201324',
                'hoten' => 'Nguyễn Võ Anh Quốc',
                'email' => 'DH52201324@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201334',
                'hoten' => 'Phan Gia Quý',
                'email' => 'DH52201334@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201341',
                'hoten' => 'Nguyễn Ngọc Quyến',
                'email' => 'DH52201341@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201345',
                'hoten' => 'Bùi Vạn Quỳnh',
                'email' => 'DH52201345@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201373',
                'hoten' => 'Phạm Ngọc Sơn',
                'email' => 'DH52201373@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201379',
                'hoten' => 'Võ Văn Sỹ',
                'email' => 'DH52201379@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201390',
                'hoten' => 'Nguyễn Tuấn Tài',
                'email' => 'DH52201390@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201391',
                'hoten' => 'Nguyễn Xuân Tài',
                'email' => 'DH52201391@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201392',
                'hoten' => 'Phạm Hữu Tài',
                'email' => 'DH52201392@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201412',
                'hoten' => 'Trần Thanh Tân',
                'email' => 'DH52201412@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201418',
                'hoten' => 'Nguyễn Duy Thái',
                'email' => 'DH52201418@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201419',
                'hoten' => 'Nguyễn Quốc Thái',
                'email' => 'DH52201419@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201431',
                'hoten' => 'Chung Nguyễn Quốc Thắng',
                'email' => 'DH52201431@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201434',
                'hoten' => 'Huỳnh Mai Việt Thắng',
                'email' => 'DH52201434@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201447',
                'hoten' => 'Lư Chí Thanh',
                'email' => 'DH52201447@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201448',
                'hoten' => 'Ngô Kiến Thanh',
                'email' => 'DH52201448@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201449',
                'hoten' => 'Nguyễn Chí Thanh',
                'email' => 'DH52201449@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201451',
                'hoten' => 'Tân Khải Thanh',
                'email' => 'DH52201451@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201467',
                'hoten' => 'Phạm Văn Thành',
                'email' => 'DH52201467@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201556',
                'hoten' => 'Nguyễn Tân Tiến',
                'email' => 'DH52201556@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201568',
                'hoten' => 'Nguyễn Hữu Tín',
                'email' => 'DH52201568@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 2,
            ],
            [
                'id' => 'DH52201569',
                'hoten' => 'Nguyễn Trọng Tín',
                'email' => 'DH52201569@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH52201579',
                'hoten' => 'Hoàng Kim Tịnh',
                'email' => 'DH52201579@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH72202462',
                'hoten' => 'Lê Thị Thanh Trúc',
                'email' => 'DH72202462@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH52201708',
                'hoten' => 'Lê Minh Tuấn',
                'email' => 'DH52201708@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH52201713',
                'hoten' => 'Nguyễn Hoàng Anh Tuấn',
                'email' => 'DH52201713@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH52201724',
                'hoten' => 'Võ Hoàng Tuấn',
                'email' => 'DH52201724@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH72202500',
                'hoten' => 'Vương Ngọc Hải Vân',
                'email' => 'DH72202500@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
            [
                'id' => 'DH52201757',
                'hoten' => 'Nguyễn Lâm Chí Vinh',
                'email' => 'DH52201757@student.stu.edu.vn',
                'password' => Hash::make('123456'),
                'trangthai' => 1,
                'manhomquyen' => 3,
                'makhoa' => 3,
            ],
        ]);
    }
}
